from django.urls import path
from core import views as CoreViews
urlpatterns = [
    path('get-all-brands', CoreViews.get_all_brands, name='get_all_brands'),
    path('create-brands', CoreViews.create_brand, name='create_brands'),
    path('update-brands', CoreViews.update_brand, name='update_brands'),
    path('delete-brands/<int:brand_id>', CoreViews.delete_brand, name='delete_brands'),
    path('get-all-coupons', CoreViews.get_all_coupons, name='get_all_coupons'),
    path('create-coupons', CoreViews.create_coupon, name='create_coupons'),
    path('update-coupons', CoreViews.update_coupon, name='update_coupons'),
    path('delete-coupons/<int:coupon_id>', CoreViews.delete_coupon, name='delete_coupons'),
    path('get-all-sizes', CoreViews.get_all_sizes, name='get_all_sizes'),
    path('create-sizes', CoreViews.create_size, name='create_sizes'),
    path('update-sizes', CoreViews.update_size, name='update_sizes'),
    path('delete-sizes/<int:size_id>', CoreViews.delete_size, name='delete_sizes'),
    path('get-all-orderStates', CoreViews.get_all_orderStates, name='get_all_orderStates'),
    path('create-orderStates', CoreViews.create_orderState, name='create_orderStates'),
    path('update-orderStates', CoreViews.update_orderState, name='update_orderStates'),
    path('delete-orderStates/<int:orderState_id>', CoreViews.delete_orderState, name='delete_orderStates'),
    path('get-all-extras', CoreViews.get_all_extras, name='get_all_extras'),
    path('create-extras', CoreViews.create_extra, name='create_extras'),
    path('update-extras', CoreViews.update_extra, name='update_extras'),
    path('delete-extras/<int:extra_id>', CoreViews.delete_extra, name='delete_extras'),
    path('get-all-categories', CoreViews.get_all_categories, name='get_all_categories'),
    path('create-categories', CoreViews.create_category, name='create_categories'),
    path('update-categories', CoreViews.update_category, name='update_categories'),
    path('delete-categories/<int:category_id>', CoreViews.delete_category, name='delete_categories'),
    path('get-all-cities', CoreViews.get_all_cities, name='get_all_cities'),
    path('create-cities', CoreViews.create_city, name='create_cities'),
    path('update-cities', CoreViews.update_city, name='update_cities'),
    path('delete-cities/<int:city_id>', CoreViews.delete_city, name='delete_cities'),
    path('get-all-countries', CoreViews.get_all_countries, name='get_all_countries'),
    path('get-all-countries-cities', CoreViews.get_all_countries_cities, name='get_all_countries_cities'),
    path('create-countries', CoreViews.create_country, name='create_countries'),
    path('update-countries', CoreViews.update_country, name='update_countries'),
    path('delete-countries/<int:country_id>', CoreViews.delete_country, name='delete_countries'),

]